name: Auto Merge Pull Requests

on:
    pull_request:
        types: [opened, reopened]
        branches:
            - main

jobs:
    merge-pr:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - name: Automatically Merge PR
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  PR_URL: ${{ github.event.pull_request.html_url }}
              run: |
                  gh pr merge "$PR_URL" --merge --auto || gh pr merge "$PR_URL" --merge
